### ISSUE TITLE
fail to run examples

### ISSUE THREAD

**Issue by yssource** [pleiszenburg/zugbruecke#22]
It seems that it is not able to load `demo_dll.dll`. And I have complied the dll by `x86_64-w64-mingw32-gcc`

- Linux localhost 4.15.6-300.fc27.x86_64
- fedora27
- x86_64-w64-mingw32-gcc

**Comment by yssource** [comment]
I think it is caused by `x86_64-w64-mingw32-gcc`.
Any one know how to make a good one dll under fedora27?

**Comment by s-m-e** [comment]
@yssource How did you compile the DLL? Looks like you used a 64 bit version of `mingw`, producing a 64 bit DLL. `zugbruecke` by default runs on top of 32 bit versions of Wine and Python for Windows. You can either try to install a 32 bit version of `mingw` and compile the DLL in 32 bit mode or configure `zugbruecke` to run in 64 bit mode (with 64 bit versions of Wine and Python for Windows), see the [`arch` parameter](http://zugbruecke.readthedocs.io/en/latest/configuration.html#configurable-parameters). 

Besides, have you tried the [basic example](https://github.com/pleiszenburg/zugbruecke#examples) given in the project's readme file? It will call a DLL (msvcrt.dll), which is provided as a part of WIne.

**Comment by yssource** [comment]
With ~i686-w64-mingw32-gcc~, now it's working.

Thanks.
