### ISSUE TITLE
test with windows api

### ISSUE THREAD

**Issue by yssource** [pleiszenburg/zugbruecke#24]
* window.py
```python
# -*- coding: utf-8 -*-
from sys import platform
import os
import sys
if any([platform.startswith(os_name) for os_name in ['linux', 'darwin', 'freebsd']]):
        import zugbruecke as ctypes
        import zugbruecke.wintypes as wintypes
elif platform.startswith('win'):
        import ctypes
        import ctypes.wintypes as wintypes
else:
        raise # handle other platforms here


api = ctypes.windll.user32

def main():
    title = 'Wine Configuration'
    api.FindWindowW.argtypes = (ctypes.c_int, wintypes.LPWSTR)
    api.FindWindowW.restype = wintypes.HWND
    window = api.FindWindowW(0, wintypes.LPWSTR(title))
    print('looking for a window: {}'.format(window))
    return


if __name__ == '__main__':
    main()

```

* how to reproduce
  1. linux-side bash running `winecfg`
  2. wine-side running `python window.py` under `wineconsole`
      OK. get the expected result
  3. linux-side running `python window.py`
      None, no result
* Result
  winecfg
![screenshot from 2018-03-18 14-42-58](https://user-images.githubusercontent.com/3756334/37563399-b7741784-2aba-11e8-9f60-fc506b2a20d2.png)

  wine-side by `wineconsole`
![screenshot from 2018-03-18 14-27-20](https://user-images.githubusercontent.com/3756334/37563368-26111b7a-2aba-11e8-9c52-f3c01acc52cd.png)
  
  linux-side 
![screenshot from 2018-03-18 14-26-41](https://user-images.githubusercontent.com/3756334/37563372-314b6004-2aba-11e8-97d6-901496e29a77.png)

**Comment by s-m-e** [comment]
@yssource I guess I understand your issue. `Wine` has a server component and a profile folder. When you run `winecfg` in bash, it will use the default profile folder (`~/.wine/`) and start a server there. `zugbruecke` on the other hand isolates itself from the default Wine folder and uses its own folder (`~/.zugbruecke/win32-wine/`) and its own server. In your example, you are running two Wine servers, and one is not knowing what the other is doing :)

You can work around it like this. Create a small bash script for starting `winecfg` properly:
```
#!/bin/bash

arch=$(python3 -c 'from zugbruecke.core.config import echo_parameter; echo_parameter("arch")')
zugbruecke_dir=$(python3 -c 'from zugbruecke.core.config import echo_parameter; echo_parameter("dir")')

dir_wine=$zugbruecke_dir/$arch-wine

export WINEARCH="$arch"
export WINEPREFIX="$dir_wine"

winecfg
```
It works just fine.

**Comment by yssource** [comment]
:100: :+1: :1st_place_medal: It's amazing. It's so GREAT of your help.

Thank you so so so much...
