### ISSUE TITLE
rpc.py raises a RuntimeError: No active exception to reraise

### ISSUE THREAD

**Issue by jtlz2** [pleiszenburg/zugbruecke#34]
@s-m-e Not sure how to handle this! Thanks for all help:

```
(1521699014.83/8a485ca8) WINE o: [routine-server] Trying call routine "func" ...
Traceback (most recent call last):
  File "./func.py", line 1079, in <module>
    ret=main()
  File "./func.py", line 903, in main
    status=func(a,b,c)
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/routine_client.py", line 120, in __call__
    self.data.arg_list_pack(args, self.argtypes_d), mem_package_list
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/rpc.py", line 97, in do_rpc
    raise result
RuntimeError: No active exception to reraise
(1521699014.83/8a485ca8) UNIX o: [session-client] TERMINATING ...
```

**Comment by s-m-e** [comment]
@jtlz2 You ran into one of the many cases where `zugbruecke` just does not produce meaningful errors. Your error was caused somewhere on the Wine side (before a function call, either in the routine for unpacking the shipped arguments or in the routine for unpacking the shipped memory) and sent back through RPC to the Unix side. So the likely root cause is that you made a mistake in the `argtypes` or `memsync` definitions - very likely the latter. Before I improve error handing, I can help you with a small hack, which will give me better debugging output. 

Have a look at the [`__call__` routine](https://github.com/pleiszenburg/zugbruecke/blob/8652a873027348c1cb25f92bc1ca97fd09a9be6d/src/zugbruecke/core/routine_server.py#L66) in the routine server class. Your error comes from either lines 75 or 78. You can wrap them into a try-except-block:

```
	try:

		# Unpack passed arguments, handle pointers and structs ...
		args_list = self.data.arg_list_unpack(arg_message_list, self.argtypes_d)

		# Unpack pointer data
		memory_handle = self.data.server_unpack_memory_list(args_list, arg_memory_list, self.memsync_d)

	except Exception as e:

		# Log status
		self.log.out('[routine-server] Unknown error!')

		# Push traceback to log
		self.log.err(traceback.format_exc())
```

This will give you a more detailed traceback. Please post it here.

**Comment by jtlz2** [comment]
(1521705503.99/314d9926) WINE o: [routine-server] Trying call routine "func" ...
(1521705503.99/314d9926) WINE o: [routine-server] Unknown error!
(1521705503.99/314d9926) WINE e: Traceback (most recent call last):
(1521705503.99/314d9926) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\routine_server.py", line 76, in __call__
(1521705503.99/314d9926) WINE e:     args_list = self.data.arg_list_unpack(arg_message_list, self.argtypes_d)
(1521705503.99/314d9926) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 75, in arg_list_unpack
(1521705503.99/314d9926) WINE e:     return [self.__unpack_item__(a[1], d) for a, d in zip(args_package_list, argtypes_list)]
(1521705503.99/314d9926) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 75, in <listcomp>
(1521705503.99/314d9926) WINE e:     return [self.__unpack_item__(a[1], d) for a, d in zip(args_package_list, argtypes_list)]
(1521705503.99/314d9926) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 344, in __unpack_item__
(1521705503.99/314d9926) WINE e:     arg_rebuilt = self.__unpack_item_struct__(arg_raw, arg_def_dict)
(1521705503.99/314d9926) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 466, in __unpack_item_struct__
(1521705503.99/314d9926) WINE e:     self.__unpack_item__(field_arg[1], field_def_dict) # parameter value
(1521705503.99/314d9926) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 367, in __unpack_item__
(1521705503.99/314d9926) WINE e:     return self.__unpack_item_array__(arg_raw, arg_def_dict)[1]
(1521705503.99/314d9926) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 422, in __unpack_item_array__
(1521705503.99/314d9926) WINE e:     raise # TODO
(1521705503.99/314d9926) WINE e: RuntimeError: No active exception to reraise
(1521705504.00/314d9926) WINE o: [routine-server] ... failed!
(1521705504.00/314d9926) WINE e: Traceback (most recent call last):
(1521705504.00/314d9926) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\routine_server.py", line 102, in __call__
(1521705504.00/314d9926) WINE e:     return_value = self.handler(*tuple(args_list))
(1521705504.00/314d9926) WINE e: UnboundLocalError: local variable 'args_list' referenced before assignment
Traceback (most recent call last):
  File "./func.py", line 1083, in <module>
    ret=main()
  File "./func.py", line 907, in main
    status=func(a,b,c)
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/routine_client.py", line 120, in __call__
    self.data.arg_list_pack(args, self.argtypes_d), mem_package_list
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/rpc.py", line 97, in do_rpc
    raise result
UnboundLocalError: local variable 'return_value' referenced before assignment
(1521705504.00/314d9926) UNIX o: [session-client] TERMINATING ...
(1521705504.00/314d9926) UNIX o: [session-client] Waiting for session-server be down ...
(1521705504.00/314d9926) UNIX o: [session-client] ... session server is down (after 0.00 seconds).
(1521705504.00/314d9926) WINE o: [mp-server] TERMINATING ...
(1521705504.00/314d9926) WINE o: [session-server] TERMINATING ...
(1521705504.00/314d9926) WINE o: [session-server] TERMINATED.
(1521705504.00/314d9926) WINE o: [mp-server] TERMINATED.
(1521705504.00/314d9926) UNIX o: [interpreter] TERMINATING ...
(1521705504.00/314d9926) UNIX o: [interpreter] Joining logging thread "out" ...
(1521705505.00/314d9926) UNIX o: [interpreter] Joining logging thread "err" ...
(1521705506.01/314d9926) UNIX o: [interpreter] Logging threads joined or timed out.
(1521705506.01/314d9926) UNIX o: [interpreter] TERMINATED.
(1521705506.01/314d9926) UNIX o: [session-client] TERMINATED.

**Comment by s-m-e** [comment]
@jtlz2 It appears to me that you're running an "older" release. My apologies - can you please update `zugbruecke` to the least release (you'd probably have to uninstall with `pip3 uninstall zugbruecke` and re-install it with `pip3 install zugbruecke` to be on the safe side) and repeat the above exercise?

**Comment by jtlz2** [comment]
@s-m-e No no my fault - I think it was due to branch-hopping. Same result?

```
(1521706362.86/71723c3a) WINE o: [routine-server] Trying call routine "func" ...
(1521706362.86/71723c3a) WINE o: [routine-server] Unknown error!
(1521706362.86/71723c3a) WINE e: Traceback (most recent call last):
(1521706362.86/71723c3a) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\routine_server.py", line 76, in __call__
(1521706362.86/71723c3a) WINE e:     args_list = self.data.arg_list_unpack(arg_message_list, self.argtypes_d)
(1521706362.86/71723c3a) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 75, in arg_list_unpack
(1521706362.86/71723c3a) WINE e:     return [self.__unpack_item__(a[1], d) for a, d in zip(args_package_list, argtypes_list)]
(1521706362.86/71723c3a) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 75, in <listcomp>
(1521706362.86/71723c3a) WINE e:     return [self.__unpack_item__(a[1], d) for a, d in zip(args_package_list, argtypes_list)]
(1521706362.86/71723c3a) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 344, in __unpack_item__
(1521706362.86/71723c3a) WINE e:     arg_rebuilt = self.__unpack_item_struct__(arg_raw, arg_def_dict)
(1521706362.86/71723c3a) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 466, in __unpack_item_struct__
(1521706362.86/71723c3a) WINE e:     self.__unpack_item__(field_arg[1], field_def_dict) # parameter value
(1521706362.86/71723c3a) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 367, in __unpack_item__
(1521706362.86/71723c3a) WINE e:     return self.__unpack_item_array__(arg_raw, arg_def_dict)[1]
(1521706362.86/71723c3a) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\data\contents.py", line 422, in __unpack_item_array__
(1521706362.86/71723c3a) WINE e:     raise # TODO
(1521706362.86/71723c3a) WINE e: RuntimeError: No active exception to reraise
(1521706362.87/71723c3a) WINE o: [routine-server] ... failed!
(1521706362.87/71723c3a) WINE e: Traceback (most recent call last):
(1521706362.87/71723c3a) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\routine_server.py", line 96, in __call__
(1521706362.87/71723c3a) WINE e:     return_value = self.handler(*tuple(args_list))
(1521706362.87/71723c3a) WINE e: UnboundLocalError: local variable 'args_list' referenced before assignment
Traceback (most recent call last):
  File "./func.py", line 1083, in <module>
    ret=main()
  File "./func.py", line 907, in main
    status=func(a,b,c)
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/routine_client.py", line 120, in __call__
    self.data.arg_list_pack(args, self.argtypes_d), mem_package_list
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/rpc.py", line 97, in do_rpc
    raise result
UnboundLocalError: local variable 'return_value' referenced before assignment
(1521706362.87/71723c3a) UNIX o: [session-client] TERMINATING ...
(1521706362.87/71723c3a) UNIX o: [session-client] Waiting for session-server be down ...
(1521706362.87/71723c3a) UNIX o: [session-client] ... session server is down (after 0.00 seconds).
(1521706362.87/71723c3a) WINE o: [mp-server] TERMINATING ...
(1521706362.87/71723c3a) WINE o: [session-server] TERMINATING ...
(1521706362.87/71723c3a) WINE o: [session-server] TERMINATED.
(1521706362.88/71723c3a) WINE o: [mp-server] TERMINATED.
(1521706362.88/71723c3a) UNIX o: [interpreter] TERMINATING ...
(1521706362.88/71723c3a) UNIX o: [interpreter] Joining logging thread "out" ...
(1521706363.88/71723c3a) UNIX o: [interpreter] Joining logging thread "err" ...
(1521706364.88/71723c3a) UNIX o: [interpreter] Logging threads joined or timed out.
(1521706364.88/71723c3a) UNIX o: [interpreter] TERMINATED.
(1521706364.88/71723c3a) UNIX o: [session-client] TERMINATED.
```

**Comment by s-m-e** [comment]
@jtlz2 Same result - this time with the right line numbers. There were too many places where this could come from. 

I **guess** I know what you're doing. The code at fault is unpacking arrays. It detects whether you are unpacking a fixed-length array of data of either one of the fundamental data types (integers, floats, ...) or a struct type. Anything else is not handled here (it's supposed to be the job of memsync - in argtypes, you'd simply specify a single void pointer instead of an array). Looks like you specified something like a fixed-length array of (void) pointers. Can you post the definition of the function call (i.e. argtypes and restype definitions)?

**Comment by jtlz2** [comment]
@s-m-e Sorry about that....

```
class A(ctypes.Structure):
    _fields_ = [("setting", ctypes.c_int),
               ("callback", ctypes.c_void_p)]

class B(ctypes.Structure):
    _fields_ = [("data_in", ctypes.c_ubyte*500),
               ("size", ctypes.c_int)]

class C(ctypes.Structure):
    _fields_ = [("data_out", ctypes.c_ubyte*10000),
               ("height", ctypes.c_int),
               ("width", ctypes.c_int),
               ("more_data_out", ctypes.c_void_p)]

    func.argtypes = (A,B,C)

    b=B(); c=C(); d=D();
    b.width=1 # [Fiddled so that b.width * b.height = constant - see #33]
    b.height=10000 #

    func.memsync = [
        {
                'p': [1,'data_out'],
                'l': [1,'Height'],
                '_t': ctypes.c_ubyte
        },
        {
                'p': [2,'data_in'],
                'l': [2,'size'],
                '_t': ctypes.c_ubyte
        }
        ]

    func.restype=ctypes.c_int

    func.memsync=... # as above
    status=func(a,b,c)
```

I am assuming the `struct` definitions that the callback, which is not used, can be assigned 'ctypes.c_void_p'...

**Comment by jtlz2** [comment]
@s-m-e What happens if (as now) I don't tell memsync about all of the pointers? :\

**Comment by s-m-e** [comment]
```
class B(ctypes.Structure):
    _fields_ = [("data_in", ctypes.c_ubyte*500),
               ("size", ctypes.c_int)]
```
@jtlz2 There is your issue: ``ctypes.c_ubyte*500``. Instead, you want something like ``ctypes.POINTER(ctypes.c_ubyte)`` (without the times 500). The same applies to ``data_out`` in your other struct definition. It's multiple mistakes you've made here. Both data fields are not **fixed length** arrays. They are pointers to "variable length" memory sections. So you basically define them as a pointer to the first element in the array, i.e. a pointer to a byte in your example. Beyond that point, you also have to allocate memory for the pointers (when you initialize instances of your structures) before you call a function. Check out [this question on SO](https://stackoverflow.com/questions/18679264/how-to-use-malloc-and-free-with-python-ctypes?rq=1) for inspiration.

**Comment by jtlz2** [comment]
@s-m-e Thanks for the clarification here and apologies that you have had to give me a ctypes lesson at the same time... Am much clearer on this now. This particular question can probably be put to bed.
