### ISSUE TITLE
Mechanism to chose wine prefix ?

### ISSUE THREAD

**Issue by stuaxo** [pleiszenburg/zugbruecke#44]
It would be handy to have a way to chose the wine prefix used.

This would be handy when I want to use a wine environment that already has some programs installed.   

(In my instance I was trying with Winamp / WACUP)

**Comment by s-m-e** [comment]
@stuaxo Good idea - I will add an option that allows a user to point to an existing wine prefix.

**Comment by stuaxo** [comment]
Great :)

It would be great to document the API the sets up zugbruecke with a wine prefix too.

Is there an easy way to check if a prefix is already setup with zugbruecke?

**Comment by s-m-e** [comment]
Currently, *zugbruecke* creates its own wine-prefix underneath its configuration folder, see [here](https://github.com/pleiszenburg/zugbruecke/blob/2a690a69522e6c3419413997590c05dac9589400/src/zugbruecke/core/wineenv.py#L140) and [here](https://github.com/pleiszenburg/zugbruecke/blob/2a690a69522e6c3419413997590c05dac9589400/src/zugbruecke/core/config.py#L95). The pattern is `{path_to_home}/.zugbruecke/{arch}-wine` where `arch` can be either `win32` (default) or `win64`. `{path_to_home}` can also be replaced by something like `/etc` if you're installing system-wide (not recommended). In the early phase of the development of this package, I was messing around with different wine configuration options (like Windows version / API level support), so I did not want to destroy a user's wine-prefix - this was one of the reasons why I have intentionally kept this stuff separated / isolated. But if you really want to use a per-existing environment, why not - I can modify the configuration logic to allow that.

**Comment by s-m-e** [comment]
Ok, I need some more time for this - it's not a 10 minute fix as I thought, unfortunately. I have hard-coded the pattern `{path_to_home}/.zugbruecke/{arch}-wine` in a few placed, i.e. I need to refactor some code before I can clean this up ...

**Comment by s-m-e** [comment]
@stuaxo I have pushed a new branch, [refactor_moduledesign](https://github.com/pleiszenburg/zugbruecke/tree/refactor_moduledesign). It is still under development and not finalized yet. **Among quite a lot of changes, I also added a new configuration parameter: ``wineprefix``.** In ``.zugbruecke.json``, you can set it to a path of your choice. Please test.

Be aware that there are significant changes to the module layout, see [change log](https://github.com/pleiszenburg/zugbruecke/blob/refactor_moduledesign/CHANGES.rst). It might be necessary to run ``wenv init`` after you have installed the package for completing the installation process. If you go through the make file (``make install`` or ``make install_link``) the latter will be done for you automatically. For more details see ``wenv help``.

**Comment by stuaxo** [comment]
Cheers, I'll give this a go.

**Comment by stuaxo** [comment]
I tried this, with the following `.zugbruecke.json`

```json
{
    "wineprefix": "test-wacup"
}
```

This didn't work as it wants an absolute path.    Would it be possible to support setting name like this, but the wineprefix still ending up in the default directory for zugbruecke wineprefixes ?

**Comment by s-m-e** [comment]
@stuaxo Thanks for testing. Yes, it's possible, but I am wondering about the semantics. `wineprefix` does not need to be absolute. Currently, it can also be relative to the current working directory. The question then becomes how you want to indicate that you want the path to be relative to something else other than the cwd. I could add another configuration option ... I am open to ideas and suggestions.

In this context, I am considering another design change related to the above: Currently, the `wineprefix` resides together with the configuration in `{path_to_home}/.zugbruecke/`. This basically means that both the `wineprefix` and the configuration can not easily be isolated for different installations of `zugbruecke` in different virtual environments. I am thinking about moving this stuff into the `shared` folder of the currently active virtual environment for improved isolation. Alternatively, this could become an optional feature as well. Thoughts and criticism are highly welcome.

**Comment by stuaxo** [comment]
Maybe support use expanduser so ~ can be used?

I can see why you may not want general env var support without a bit more thought.

**Comment by stuaxo** [comment]
Maybe where the prefix is saved and what it's called are two settings (with sane defaults)?

**Comment by s-m-e** [comment]
Feature released as part of new [wenv package](https://github.com/pleiszenburg/wenv). zugbruecke will adopt it in next release.

**Comment by stuaxo** [comment]
Fantastic, this seems to solves the tricky problems of getting python in wine up and running.
