### ISSUE TITLE
Pickling error on calling dll method

### ISSUE THREAD

**Issue by vishalapte** [pleiszenburg/zugbruecke#46]
```
~/virtenvs/fm3/lib/python3.7/site-packages/zugbruecke/core/routine_client.py in __call__(self, *args)
    118                 # Actually call routine in DLL! TODO Handle kw ...
    119 		return_dict = self.__handle_call_on_server__(
--> 120                         self.data.arg_list_pack(args, self.argtypes_d), mem_package_list
    121 			)
    122 

~/virtenvs/fm3/lib/python3.7/site-packages/zugbruecke/core/rpc.py in do_rpc(*args, **kwargs)
     89 
     90                         # Send request to server
---> 91                         self.client.send((name, args, kwargs))
     92                         # Receive answer
     93                         result = self.client.recv()

/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py in send(self, obj)
    204         self._check_closed()
    205         self._check_writable()
--> 206         self._send_bytes(_ForkingPickler.dumps(obj))
    207 
    208     def recv_bytes(self, maxlength=None):

/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/reduction.py in dumps(cls, obj, protocol)
     49     def dumps(cls, obj, protocol=None):
     50         buf = io.BytesIO()
---> 51         cls(buf, protocol).dump(obj)
     52         return buf.getbuffer()
     53 

PicklingError: Can't pickle <class '__main__.c_double_Array_3'>: attribute lookup c_double_Array_3 on __main__ failed
```

My code is as follows:

```
class RBCombinedValueWrapper(object):
    def __init__(self):
        fullpath = os.path.join(settings.BASE_DIR, 'apps/avm/dll/RenewablesLibrary.dll')
        self.obj = cdll.LoadLibrary(fullpath).RBCombinedValueWrapper
        self.obj.argtypes = (
            c_double,
            c_double,
            POINTER(c_double),
            POINTER(c_double),
            POINTER(c_double),
            POINTER(c_double),
            c_double,
            POINTER(POINTER(c_double)),
            POINTER(POINTER(c_double)),
            POINTER(POINTER(c_double)),
            POINTER(POINTER(c_double)),
            POINTER(c_double),
            POINTER(POINTER(c_double)),
            POINTER(POINTER(c_double)),
        )
        self.obj.restype = POINTER(c_double)

        self.valdate = None
        self.expdate = None
        self.prices = None
        self.vols = None
        self.corrs = None
        self.days = None
        self.rate = 0
        self.weekday_scalar = Scalars()
        self.weekend_scalar = Scalars()
        self.asset = BatteryAsset()

        self.pk_profile = (c_double * 16 * 12)()
        for m in range(12):
            for h in range(16):
                self.pk_profile[m][h] = 1

        self.op_profile = (c_double * 8 * 12)()
        for m in range(12):
            for h in range(8):
                self.op_profile[m][h] = 1

    def calculate(self):
        result = self.obj(
                self.valdate,
                self.expdate,
                (c_double * len(self.prices))(*self.prices),
                (c_double * len(self.vols))(*self.vols),
                (c_double * len(self.corrs))(*self.corrs),
                (c_double * len(self.days))(*self.days),
                self.rate,
                self.weekday_scalar.getarray(True, False),
                self.weekday_scalar.getarray(False, True),
                self.weekend_scalar.getarray(True, False),
                self.weekend_scalar.getarray(False, True),
                self.asset.getarray(),
                self.weekday_scalar.getarray(True, False),
                self.weekday_scalar.getarray(False, True),
        )
        return result
```

**Comment by s-m-e** [comment]
This should actually work as far as I can tell from your code. Which version of zugbruecke are you using?

**Comment by vishalapte** [comment]
```
($) python --version
Python 3.7.4
```

`zugbruecke==0.0.14`

**Comment by s-m-e** [comment]
Ok, thanks. Can you post the signature / header of `RBCombinedValueWrapper` (the DLL function) and possibly the source code of `RBCombinedValueWrapper.weekend_scalar.getarray` (from your Python class)?

**Comment by vishalapte** [comment]
```
class Scalars(object):
    def __init__(self):
        self.scalars = [[1.0] * 24] * 12

    def getarray(self, peak, offpeak):
        w = 12
        h = 0
        hours = []
        if peak:
            h = h + 16
            hours.extend(range(6, 22))
        if offpeak:
            h = h + 8
            hours.extend([0, 1, 2, 3, 4, 5, 22, 23])

        result = (ctypes.c_double * h * w)()
        for x in range(w):
            for y, h in enumerate(hours):
                result[x][y] = self.scalars[x][h]

        print(result)
        return result
```

I do not have access to the actual code and am trying to get the header for the DLL function. What I have is...

```
public static double[,] RBCombinedValueWrapper(
    double valuedate, 
    double expiration,
    double[] Prices,
    double[] Vols,
    double[] Corrs,
    double[] wrapperTotDays,
    double r,
    double[,] wdpk,
    double[,] wdop,
    double[,] wepk,
    double[,] weop,
    double[] asset,
    double[,] a,
    double[,] b
    )
```

returns `double[,] resultPub = new double[54, 1];`

**Comment by s-m-e** [comment]
`public static double[,]` looks suspiciously like Java, though I have not seen the `[,]` notation before. I assume it's the equivalent of `[][]` (?). Are you actually dealing with a DLL written in C or a similar language or are you trying to call Java code?

Besides, I can see a few conceptual mistakes in your code. E.g. you are configuring the function with `POINTER(POINTER(c_double))` at some points. However, you're passing stuff like `(ctypes.c_double * h * w)( ... )`, which is strictly speaking a flattened 1D data type. You would actually pass a single pointer instead of a pointer to an array of pointers / to another pointer.

Your 1D and 2D data types appear to not have deterministic sizes (fixed lengths). `getarray` for instance produces dynamically sized arrays depending on its parameters. This is where you need implement memory synchronization for `zugbruecke`, because it needs to synchronize memory between two independent processes (one on top of OS X in your case and one on top of Wine). The keyword is [`memsync`](https://zugbruecke.readthedocs.io/en/latest/memsync.html).

Your function definition could theoretically be sufficient to reconstruct the header. However, any further documentation on what the function expects and does with the data would be extremely helpful.

**Comment by vishalapte** [comment]
I will attempt to secure more documentation. I appreciate your patience.

**Comment by s-m-e** [comment]
No problem. I should add that the `Pickling error` that you initially posted is actually triggered by wrongly configuring and calling the function. Your function is configured to use a pointer type, i.e. `POINTER( ...)`. It actually expects a real pointer then which you get by running `pointer( .. )` on your data (yes, upper case for the type and lower case for the data).

**Comment by vishalapte** [comment]
1. I have specified the dimensions of each array in `argtypes`. Example: `POINTER(c_double * 16 * 8)` instead of `POINTER(POINTER(c_double))`.
2. Can I use a flattened 1D array (like the current output of `getarray()` with `pointer()` to satisfy `POINTER(c_double * 16 * 12)`

Will I still need to use `memsync` if all argtypes are of deterministic/fixed lengths?

The above changes fixed the Pickling error and instead returns `TypeError: a float is required`

Thanks for reviewing.

[wrapper.txt](https://github.com/pleiszenburg/zugbruecke/files/3464056/wrapper.txt)

**Comment by s-m-e** [comment]
If you're using fixed length arrays (1D or multidimensional), you do not need to use `memsync`. See [this test](https://github.com/pleiszenburg/zugbruecke/blob/v0.0.14/tests/test_gauss_elimination.py) for example. So far, from a superficial look, your code is ok. However, this only makes sense if your corresponding DLL function also [expects fixed length arrays](https://github.com/pleiszenburg/zugbruecke/blob/v0.0.14/demo_dll/demo_dll.h#L126). Based on the Java (?) sample code you provided earlier, I *assume* that this is not the case. It's likely supposed to consume dynamically sized arrays (again *guessing* from the context).

As far as the `TypeError` exception is concerned, please provide the *full* traceback (all the way up to and including your code). I would also help if you were able to share the actual DLL file.

If sharing the full code base, documentation and most importantly the actual DLL file under the umbrella of an NDA for instance in the form of commercial support is an option for you, feel free to send me [a direct email](http://pleiszenburg.de/#contact). This way I do not have to guess blindly in the dark and you might end up with an actually working piece of code significantly faster than with trial and error.
