### ISSUE TITLE
`zugbruecke` depends on bash

### ISSUE THREAD

**Issue by s-m-e** [pleiszenburg/zugbruecke#48]
... for which there is no good reason. [`wine-python`](https://github.com/pleiszenburg/zugbruecke/blob/v0.0.14/scripts/wine-python) and similar scripts [can be implemented in pure Python](https://docs.python.org/3/library/os.html#os.execvpe).

**Comment by s-m-e** [comment]
Fix released as part of new [wenv package](https://github.com/pleiszenburg/wenv). zugbruecke will adopt it in next release.

**Comment by Artoria2e5** [comment]
It doesn't depend on bash per se; the range of syntax used is just `/bin/sh`, which should be there on every system that is able to run wine. A change of shebang will do.

But eh, wenv does look better.

**Comment by s-m-e** [comment]
> But eh, wenv does look better.

@Artoria2e5 Glad to hear that :) `wenv` works based on [os.exec*](https://docs.python.org/3/library/os.html#os.execl), without going through any kind of shell.

**Comment by s-m-e** [comment]
Solved in v0.1.0.
