### ISSUE TITLE
"wenv init" requires internet connection

### ISSUE THREAD

**Issue by s-m-e** [pleiszenburg/zugbruecke#55]
An "offline option" can be extremely useful in certain environments.

Currently, `wenv init` will download a ZIP-file containing an embeddable version of the CPython interpreter for Windows as well as `get-pip.py`. The user could download those files instead and provide them to `wenv init` through local paths.

Next, `wenv init` calls `wenv pip` to install further packages. `wenv pip` could, just like the regular `pip`, easily be instructed to use a local package repository or cache.

**Comment by jayvdb** [comment]
This is probably the cause of my rpm `%check` failures at https://build.opensuse.org/package/show/home:jayvdb:py-bridge/python-zugbruecke

If we can get this solved, I can run zugbruecke tests on the openSUSE test grid, which includes arms, ppc, etc, which addresses some of your other outstanding issues.

**Comment by s-m-e** [comment]
Thanks for your work and comment. I very much like the idea of running this on OBS. There is some stuff to unpack here. Bottom line - it is NOT related to THIS issue here ;) I am going to break this down into new issues all referencing this one.

**Comment by s-m-e** [comment]
Now tracked in [wenv#1](https://github.com/pleiszenburg/wenv/issues/1).
