### ISSUE TITLE
`OSError: link could not be created` when installed as wheel

### ISSUE THREAD

**Issue by melvyn2** [pleiszenburg/zugbruecke#81]
This package expects to be installed as an egg, but gets installed as a wheel instead following the installation instructions in the README (`pip install git+https://github.com/pleiszenburg/zugbruecke.git@develop`). Wheels create a directory like `zugbruecke-0.1.0.dist-info` instead of the `zugbruecke.egg-info` that this package expects (https://github.com/pleiszenburg/zugbruecke/blob/develop/src/zugbruecke/core/wenv.py#L109)

**Comment by s-m-e** [comment]
Fixed in v0.1.0 (due to be released later today).
