### ISSUE TITLE
Argument wrapping for pickling

### ISSUE THREAD

**Issue by JuliaSprenger** [pleiszenburg/zugbruecke#90]
Hi there! I am very happy to have discovered this package! I am trying to get a small Python Package including a windows dll to work on a linux machine following the platform-independent instructions in your [documentation](https://zugbruecke.readthedocs.io/en/latest/examples.html#platform-independent-code). However, when running the code on a linux machine i still get an argument error:
```sh
  File "pypl2/pypl2_example.py", line 45, in <module>
    spkinfo, evtinfo, adinfo = pl2_info(filename)
  File "pypl2/pypl2api.py", line 413, in pl2_info
    handle = p.pl2_open_file(filename)
  File "pypl2/pypl2lib.py", line 157, in pl2_open_file
    self.result = self.pl2_dll.PL2_OpenFile(pl2_file.encode('ascii'), byref(self.file_handle))
  File "miniconda3/envs/pypl2/lib/python3.8/site-packages/zugbruecke/core/routine_client.py", line 128, in __call__
    return_dict = self._call_on_server(
  File "miniconda3/envs/pypl2/lib/python3.8/site-packages/zugbruecke/core/rpc.py", line 69, in call_rpc_server
    self._client.send((name, args, kwargs))
  File "miniconda3/envs/pypl2/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "miniconda3/envs/pypl2/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle 'CArgObject' object

Process finished with exit code 1
```

I couldn't test the functionality of the original code as I don't have access to a windows machine, so I can only assume this error does not occur on a windows system. Is this an issue on the `zugbruecke` side of not properly converting arguments before pickling or is it just not possible to provide arguments by reference with `zugbruecke`?

I am using the following versions: `Python 3.8` (conda), `zugbruecke 0.1.0`, `wine 5.0` (Ubuntu 5.0-3ubuntu1)
The complete example code can be found [here](https://github.com/JuliaSprenger/pypl2/tree/enh/linux), including the `pypl2_example.py` script and the example data at `data/4chDemoPL2.pl2`.

**Comment by s-m-e** [comment]
Welcome to this little project. At a first glace,  I can see a few *potential* issues, though, before I dig any deeper: Does does code work directly on Wine (as if it was running on Windows directly)? Testing this is usually a good first troubleshooting step. `zugbruecke` is build on top of a package called `wenv` which allows to run a Windows-build of Python itself directly on top of `Wine`, see [documentation](https://wenv.readthedocs.io/en/latest/). You technically already have `wenv` installed as a dependency so it should be *relatively* easy to give it a go. `wenv` runs in 32bit mode by default, so you might need to tell it to run in 64bit mode if your DLL is 64bit.

**Comment by JuliaSprenger** [comment]
Hi @s-m-e. Thanks for the suggestion to look further into `wenv`. I fixed the example such that is is now working when running it directly with `wenv`. However, I still get the same error as described above when trying to run the example via `zugbruecke`.

**Comment by JuliaSprenger** [comment]
Hi again! I also changed the code to use an instance of the `zugbruecke.CTypeSession` in the hope this might solve the Argemunt issue. So far I still get the same errors as reported above. @s-m-e Do you have any hints on what to try next to be able to run the example code?

**Comment by s-m-e** [comment]
Ran the code directly on wenv/Wine and reproduced the issue with `zugbruecke`. It appears that `zugbruecke` behaves as designed, which is not a good thing in your context. [Here](https://github.com/JuliaSprenger/pypl2/blob/b91ee574404f532854513323bad8fee5e4d521d2/pypl2lib.py#L168), the function `pl2_dll.PL2_OpenFile` is called for the first time - unconfigured, i.e. no `argtypes` or `restype` is set prior to the call. *Usually*, the original `ctypes` will treat arguments as integers in this case which is also what `zugbruecke` does. However, what you are actually passing is string buffers / character arrays. Apparently, the original `ctypes` is a bit more intelligent in how it handles those if no configuration is given. `zugbruecke`, without configuration given, falls apart though.

The following solves part of your issue(s) and explains the wider problem. In `pypl2lib.py`, in the contructor of `PyPL2FileReader`, right after attaching to `pl2_dll`, past line 153, I am configuring the `PL2_OpenFile` as follows, telling it that the path is a zero-terminated string buffer (and that the file handle is in fact a pointer):

```python
        self.pl2_dll.PL2_OpenFile.argtypes = (
            POINTER(c_char),
            POINTER(c_int),
        )
        self.pl2_dll.PL2_OpenFile.memsync = [
            {
                'p': [0], # pointer argument
                'n': True, # null-terminated string flag
            }
        ]
```

Further down in `pl2_open_file`, its call changes from

```python
        self.result = self.pl2_dll.PL2_OpenFile(pl2_file.encode('ascii'), byref(self.file_handle))
```

to

```python
        self.result = self.pl2_dll.PL2_OpenFile(
            create_string_buffer(pl2_file.encode('ascii')),
            byref(self.file_handle),
        )
```

where `create_string_buffer` must also be imported from `ctypes`.

Those two fixes bring you past your initial issue but right into the next one of the same kind ;) Your code calls a number of functions from `pl2_dll` basically without configuring any of them first. Somehow, the original author of this code, despite of working with `ctypes` in a really odd way, good lucky with this approach. For this code to work in `zugbruecke`, you will have to fix it in a number of places. Not sure if anything beyond the missing configuration is broken, but this is what I would do next. Keep cross-checking your fixes by running the code directly on `wenv` so you know that original `ctypes` does not suddenly do something fishy ...

**Comment by JuliaSprenger** [comment]
Hi @s-m-e Thanks for looking into this and the detailed explanation. I will try to add the correct `argtypes` and `memsync` configuration to all methods called. I might come back here for some details of that, but thanks already for the diagnosing the issue.

**Comment by JuliaSprenger** [comment]
Hi @s-m-e I started adding `argtypes` and `memsync` configuration to the dll methods. However, I didn't succeed in specifying a Structure to be memory syncronized that itself contains a structure, e.g. [here](https://github.com/JuliaSprenger/pypl2/blob/87df5ce5741a861b23ee4a5623d43b524757a09a/pypl2lib.py#L297).  If I understood the [custom pointer type documentation](https://zugbruecke.readthedocs.io/en/latest/memsyncattr.html#key-t-data-type-of-pointer) correctly, this should be possible, but I get a KeyError in that case:
```
memsync_d["_t"] = self.cache_dict["struct_type"][memsync_d["t"]]
KeyError: 'tm'
```
Do I need to register the custom pointer type somehow for this to work properly?

**Comment by s-m-e** [comment]
@JuliaSprenger Indeed, this part is a broken ... Ironically, I came across this issue only a couple of hours earlier myself and am testing a potential fix at the moment. Stay tuned.

**Comment by s-m-e** [comment]
Can you point me to the part of your code where this problem occurs for you?

**Comment by s-m-e** [comment]
If you want to check out the bleeding edge (still lots of cleanups required before release), the test suite just passed. Branch name is `feature_argdeftype`. What you are looking for probably looks similar to [this test](https://github.com/pleiszenburg/zugbruecke/blob/6704cfeca55a62e2f5fe2307d8bd73b25a6cba6e/tests/test_vector3d_add.py#L154). Memsync had its issues with syncing entire structures. It caches struct type definitions to be able to determine their size - this is where the breakage happened. Previously, you had to specific the struct type's name and id - which did not really work out. Now, the struct type itself can be provided in the memsync directive, which should make things a lot easier and eliminate the cache miss (key error) that you were seeing.

**Comment by JuliaSprenger** [comment]
Hi @s-m-e! I tested the changes in the `feature_argdeftype` branch and this indeed brings me beyond the Structure KeyError, but directly into the next one, of which I am not sure if it is related to the structure definition or some wrong usage of `zugbruecke`:
```
  File "pypl2/pypl2_example.py", line 50, in <module>
    spkinfo, evtinfo, adinfo = pl2_info(filename)
  File "pypl2/pypl2api.py", line 423, in pl2_info
    res = p.pl2_get_file_info(handle, file_info)
  File "pypl2/pypl2lib.py", line 383, in pl2_get_file_info
    self.result = self.pl2_dll.PL2_GetFileInfo(c_int(file_handle), byref(pl2_file_info))
  File "zugbruecke/core/routine_client.py", line 119, in __call__
    self._configure()
  File "zugbruecke/core/routine_client.py", line 230, in _configure
    _ = self._configure_on_server(
  File "zugbruecke/core/rpc.py", line 74, in call_rpc_server
    raise result
KeyError: 'structtype_277a47e8bb44ae30'
```

**Comment by s-m-e** [comment]
My apologies, I am beginning to understand what else happens in your code. I should add a chapter to the docs explaining when `memsync` is required and when it is not. You are using it in places, as far as I can tell, where you for the most part likely do not need it ...

Looking at [the code you posted yesterday](https://github.com/JuliaSprenger/pypl2/blob/87df5ce5741a861b23ee4a5623d43b524757a09a/pypl2lib.py#L297), you are using `memsync` on virtually every pointer. The concept works a little different, tough: `memsync` deals with chunks of memory of arbitrary size, e.g. arrays of arbitrary length or strings of arbitrary length. For everything else where `ctypes.sizeof(your_argument_type)` would give a meaningful result right out of the gate, `memsync` is not required. I.e. `ctypes.POINTER(your_struct_type)` is just fine on its own *as long as it is only a single struct and does not refer to an array of structs*. `ctypes.POINTER(ctypes.c_int * 10)` is also fine because it is an array of fixed length where the size can clearly be deduced from the type itself. In contrast, if any of your arguments (or field in a struct) refer to an array of e.g. double floats of arbitrary length, where the length is e.g. provided via another argument (or field in a struct), then this very argument (or field in a struct) is a candidate for `memsync`. Null-terminated string buffers must also be indicated because a string (file names and paths in your case) have arbitrary length. For strings you do not have to provide a length (or where to find it) - here the indication that it is null/zero-terminated is enough for `memsync`.

`zugbruecke` manages (isolated) memory spaces in two separate processes (one directly on Linux, one on Wine), see [memory protection](https://en.wikipedia.org/wiki/Memory_protection), so technically it translates pointers from one isolated space of memory to another while also copying memory contents back and forth. It tries to figure out as much as possible on its own, hence the idea that when the size (i.e. the amount of memory to be copied) can be deduced on its own, `zugbruecke` will do so. `memsync` was born because sometimes you are dealing with things where the size is dynamic and can not be deduced from the type itself but rather from the data and/or different parameters *per function call*.

**Comment by JuliaSprenger** [comment]
Hi @s-m-e! I indeed thought that memsync is required for all dll functions to be called. Thanks for the explanations! I removed the non required memsync entries in my feature branch again and replaced them by simpler definitions where appropriate. But I still struggle with the definition of `argtypes`. As soon as I add an `argtypes` configuration for the `PL2_GetFileInfo` the code does not work any more with plain `wenv` [here](https://github.com/JuliaSprenger/pypl2/blob/d4cc9a3e6ab63f8f1de6f1065ff92ae8cdcbdb10/pypl2lib.py#L247). However, I think for using `zugbruecke` this statement seems mandatory. Any idea on how to define `argtypes` such that the code works with plain `wenv` as well as `zugbruecke`?

**Comment by s-m-e** [comment]
Judging by the function call ...

```python
self.result = self.pl2_dll.PL2_GetFileInfo(
    c_int(file_handle),  # passed by value, likely not a pointer (though ctypes **can** implicitly turn this into a pointer ...)
    byref(pl2_file_info),  # passed via a "light" pointer in ctypes terms
)
```
... I'd say the first argument is likely not a pointer. Try the following signature:

```python
self.pl2_dll.PL2_GetFileInfo.argtypes = (
    c_int,
    POINTER(PL2FileInfo),
)
```

**Comment by JuliaSprenger** [comment]
Hi @s-m-e, thanks! Not using a pointer seems the correct way to use the dll here.
I am now trying to  load  FileInfo struct via the dll without using the extensive memsync definition from the beginning, but relying on the automatic memory handling via `zugbruecke`. However, I am not sure if the memory handling for `c_char` arrays of defined length is handled correctly as `zugbruecke` can not unpack the `FileInfo` struct field(s) which are of type `c_char *256`. The log of the error is here:
```
(1672134652.07/3b888067) UNIX o: {'args': [c_int(1), <cparam 'P' (0x1cb8370)>],
(1672134652.07/3b888067) UNIX o:  'packed_args': [1,
(1672134652.07/3b888067) UNIX o:                  [('m_CreatorComment', b''),
(1672134652.07/3b888067) UNIX o:                   ('m_CreatorSoftwareName', b''),
(1672134652.07/3b888067) UNIX o:                   ('m_CreatorSoftwareVersion', b''),
(1672134652.07/3b888067) UNIX o:                   ('m_CreatorDateTime',
(1672134652.07/3b888067) UNIX o:                    [('tm_sec', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_min', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_hour', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_mday', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_mon', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_year', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_wday', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_yday', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_isdst', 0)]),
(1672134652.07/3b888067) UNIX o:                   ('m_CreatorDateTimeMilliseconds', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_TimestampFrequency', 0.0),
(1672134652.07/3b888067) UNIX o:                   ('m_NumberOfChannelHeaders', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_TotalNumberOfSpikeChannels', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_NumberOfRecordedSpikeChannels', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_TotalNumberOfAnalogChannels', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_NumberOFRecordedAnalogChannels', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_NumberOfDigitalChannels', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_MinimumTrodality', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_MaximumTrodality', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_NumberOfNonOmniPlexSources', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_Unused', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_ReprocessorComment', b''),
(1672134652.07/3b888067) UNIX o:                   ('m_ReprocessorSoftwareName', b''),
(1672134652.07/3b888067) UNIX o:                   ('m_ReprocessorSoftwareVersion', b''),
(1672134652.07/3b888067) UNIX o:                   ('m_ReprocessorDateTime',
(1672134652.07/3b888067) UNIX o:                    [('tm_sec', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_min', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_hour', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_mday', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_mon', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_year', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_wday', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_yday', 0),
(1672134652.07/3b888067) UNIX o:                     ('tm_isdst', 0)]),
(1672134652.07/3b888067) UNIX o:                   ('m_ReprocessorDateTimeMilliseconds', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_StartRecordingTime', 0),
(1672134652.07/3b888067) UNIX o:                   ('m_DurationOfRecording', 0)]],
(1672134652.07/3b888067) UNIX o:  'packed_mempkgs': []}
(1672134652.07/3b888067) WINE o: [routine-server] Trying to call routine "PL2_GetFileInfo" in DLL file "/home/sprengerj/repos/pypl2/bin/PL2FileReader.dll" ...
(1672134652.07/3b888067) WINE o: [routine-server] ... call preparation failed!
(1672134652.08/3b888067) UNIX o: [session-client] TERMINATING ...
(1672134652.08/3b888067) WINE o: [rpc-server] TERMINATING ...
(1672134652.08/3b888067) WINE o: [session-server] TERMINATING ...
(1672134652.08/3b888067) WINE o: [session-server] TERMINATED.
(1672134652.08/3b888067) WINE o: [rpc-server] TERMINATED.
(1672134652.08/3b888067) UNIX o: [interpreter] TERMINATING ...
(1672134652.08/3b888067) UNIX o: [interpreter] Ensure process has terminated, waiting ...
(1672134652.08/3b888067) WINE o: [rpc-server] OSError: Socket likely closed.
(1672134652.09/3b888067) UNIX o: [interpreter] ... terminated on its own after 0.01 seconds.
(1672134652.08/3b888067) WINE e: Traceback (most recent call last):
(1672134652.08/3b888067) WINE e:   File "C:\python-3.7.4.stable\lib\site-packages\zugbruecke\core\data\arg_contents.py", line 609, in _unpack_struct
(1672134652.08/3b888067) WINE e:     value,  # field value
(1672134652.08/3b888067) WINE e: TypeError: expected bytes, c_char_Array_256 found
(1672134652.08/3b888067) WINE e: During handling of the above exception, another exception occurred:
(1672134652.08/3b888067) WINE e: Traceback (most recent call last):
(1672134652.08/3b888067) WINE e:   File "C:\python-3.7.4.stable\lib\site-packages\zugbruecke\core\routine_server.py", line 106, in call
(1672134652.08/3b888067) WINE e:     packed_args, self._argtypes, self._convention
(1672134652.08/3b888067) WINE e:   File "C:\python-3.7.4.stable\lib\site-packages\zugbruecke\core\data\arg_contents.py", line 110, in unpack_args
(1672134652.08/3b888067) WINE e:     for arg, argtype in zip(args, argtypes)
(1672134652.08/3b888067) WINE e:   File "C:\python-3.7.4.stable\lib\site-packages\zugbruecke\core\data\arg_contents.py", line 110, in <listcomp>
(1672134652.08/3b888067) WINE e:     for arg, argtype in zip(args, argtypes)
(1672134652.08/3b888067) WINE e:   File "C:\python-3.7.4.stable\lib\site-packages\zugbruecke\core\data\arg_contents.py", line 461, in _unpack_item
(1672134652.08/3b888067) WINE e:     item = self._unpack_struct(item, itemtype)
(1672134652.08/3b888067) WINE e:   File "C:\python-3.7.4.stable\lib\site-packages\zugbruecke\core\data\arg_contents.py", line 617, in _unpack_struct
(1672134652.08/3b888067) WINE e:     ctypes.cast(value, ctypes.c_void_p),
(1672134652.08/3b888067) WINE e: TypeError: expected bytes, c_void_p found
```

Here the field `'m_CreatorComment'` is packed as a byte string, but in the struct definition its represented as a `c_char` *256 causing the following inconsistency:`TypeError: expected bytes, c_char_Array_256 found`. Is this a bug in `zugbruecke`, a wrong definition of the struct or can adding a `memsync` configuration change the packing and unpacking of the struct here?

I tried adding the complete struct to be memsynced via
```

**Comment by s-m-e** [comment]
No `memsync` required, zugbruecke should handle this just fine just like ctypes. It's one of many stupid edge cases of ctypes that you have to get right for this one. Took me ages to understand, do not worry ... ctypes types like `c_char` can be multiplied to indicate arrays. But wait, it gets really weird if you look at what happens in reality: By multiplying a class, this is what `c_char` is, you are getting a new class. From which you can create an instance, in your case a buffer of fixed, defined length. This is where you have to copy your bytes into before passing it on to the DLL.

Consider the following example:

```python
from ctypes import c_char  # or zugbruecke.ctypes ...

data = 'foo'
buffer_len = 256

c_char_array = c_char * buffer_len  # array type (used for argtypes)
buffer = c_char_array()  # create array buffer from type
data_bytes = data.encode('utf-8')  # convert string to bytes, use right encoding (ASCII in your case?)

assert len(data_bytes) < buffer_len  # just for demonstration purposes

buffer[:len(data_bytes)] = data_bytes  # write bytes into buffer, pass buffer to your DLL (via field in struct)

print(buffer, buffer[:])  # just for demonstration purposes
```

If you prepare your buffer (`m_CreatorComment`) along those lines, it should work.

**Comment by JuliaSprenger** [comment]
Hi @s-m-e Thanks for the details! I added some code [here](https://github.com/JuliaSprenger/pypl2/blob/8168b642d17dbc367ee8e9aa3695b52d7f85586f/pypl2lib.py#L253) to fix the type of fields before passing the struct to the dll. However, it seems impossible to replace impossible to [replace a field of a struct by another field](https://github.com/JuliaSprenger/pypl2/blob/8168b642d17dbc367ee8e9aa3695b52d7f85586f/pypl2lib.py#L264), as this results in an `TypeError: expected bytes, c_char_Array_256 found`.
In my understanding it would be necessary to tweak the definition of the struct itself to generate consistent field types from the beginning, but I am not sure how to achieve this as already instantiating the struct with a field value of the correct types create an error, e.g. in `PL2FileInfo(m_CreatorComment=(c_char*256)())`. At what point would you attempt to fix this issue?

**Comment by s-m-e** [comment]
Reading your code once more, I actually was not sure anymore how to do this correctly. You found a gap in my test suite. Turns out there is yet another edge case in ctypes that I did not know about. I passionately hate this module. What I told you about buffers / arrays of fixed length is basically correct for just about everything, integer arrays, float arrays, pointers to char arrays, char arrays passed by value as function arguments directly - just not for char arrays of fixed size which are *not* pointers and passed within a struct. Wt... You were close, you actually have to set the struct fields to plain Python `bytes` objects (which can be shorter than the fixed length buffer underneath). No copying into buffers required - actually, not even allowed.

The good news: I added [a bunch of new test cases](https://github.com/pleiszenburg/zugbruecke/blob/develop/tests/test_fixedlength_string_no_pointer.py) showing what you want to do, going through all variations I could think of.

The bad news: *zugbruecke* does crash for tests 2 and 3, the ones which use structs as you do.  I'll look into it, just not sure how much of a fix is needed.

**Comment by s-m-e** [comment]
Fixed, only small changes required. Use branch `develop`. Attempting to release a new version, still troubleshooting CI though.

The tests you can use as a reference can now be found [here](https://github.com/pleiszenburg/zugbruecke/blob/1b8e0358da3a51fb0d8293f87ecbedde5f4ba14e/tests/test_fixedlength_string_no_pointer.py#L277) and [here](https://github.com/pleiszenburg/zugbruecke/blob/1b8e0358da3a51fb0d8293f87ecbedde5f4ba14e/tests/test_fixedlength_string_no_pointer.py#L349).

**Comment by s-m-e** [comment]
Just released v0.2.0, containing all mentioned fixes.

**Comment by s-m-e** [comment]
Released v0.2.1, with a few more fixes related to char arrays and struct objects, among others, which could be relevant for you.

**Comment by JuliaSprenger** [comment]
Hi @s-m-e, thanks for the new release! I finally managed to get my code running with zugbruecke yielding the same results as running it directly via wenv. Thanks for the quick responses and the effort!

**Comment by s-m-e** [comment]
Thanks for the feedback!

**Comment by JuliaSprenger** [comment]
Hi @s-m-e again. It seems I was a bit too quick in concluding everything is running as expected. I again found some discrepancies between the plain `wenv` and `zugbruecke` results and figured out that I probably still have to use `memsync` at some points, as some of the dll functions receive arrays of different length at different function calls. I tried to define the length of the arrays via the custom `func` option, but this yields an `TypeError: object of type 'CArgObject' has no len()` Error.
For debugging I set up a minimal failing example [here](https://github.com/JuliaSprenger/pypl2/blob/minimal_examples/minimal_failing_example_1.py), that runs smoothly using `wenv python minimal_failing_example_1.py`.
Do I see this correctly that `memsync` is required in this case? And if yes, how is the usage of `func` for flexible array length calculation intended? I could not find any tests that cover a comparable case to see how `func` should be used in this case. Is there a more extensive example that can help for this case?

**Comment by s-m-e** [comment]
Thanks for the example, this helps a lot. I can try to have a closer look at it over the weekend. In the meantime, just a few quick notes from the top of my head while reading your code:

- `memsync` in line 35 appears to be correct.

- Lines 53 and 61: You are configuring the exact same function multiple times in a for loop. Not an actual problem but also not necessary. You can move this stuff out of the loop. 

- Lines 69 & 70 as well as lines 75 & 76: `memsync` is likely required, yes. The lambdas are only required if the length is computed from multiple parameters. In your case, there is always (as far as I understand) exactly one argument providing the length so you can remove the ~~`t`~~ `func` parameters, lines 70 and 76, entirely. Line 69 should then simply read `'l': [X],` (no list in a tuple, just a list). Similarly, line 76 should simply read `'l': [Y],`. Now `X` and `Y` should be substituted by the correct values. Right now, you're telling `memsync` that the location in memory, i.e. the pointer, is also the length of the memory section to be synchronized (the values given for `p` and `l` are identical in both cases). This does not make sense and explains your errors. I am *guessing* that the parameter in line 56 carries the length information so `X` and `Y` should be `2` I *guess* (the 3rd argument counted zero-based).

If my explanation *here* makes sense to you I likely need to fix/improve the documentation. I [recently updated it](https://zugbruecke.readthedocs.io/en/latest/memsyncattr.html), also [here](https://zugbruecke.readthedocs.io/en/latest/memsyncintro.html) and [here](https://zugbruecke.readthedocs.io/en/latest/memsyncprotocol.html), but any suggestions or - better - actual contributions are highly welcome. I came up with this mess so I am likely not seeing its quirks and gaping holes ...

---

EDIT: Initially, I wrote that you can remove the `t` parameters in your `memsync` directives. It's actually the `func` parameters that can be removed. The line numbers are correct though.

**Comment by s-m-e** [comment]
Your use-case is pretty similar to [this basic test](https://github.com/pleiszenburg/zugbruecke/blob/3cf84f9a27941de066e90944f5160c4fe77e4936/tests/test_memsync_minimal.py#L83).

In comparison, the `func` parameter only makes sense if the length is computed from multiple arguments (hence the tuple of lists in this case), see [this more complex test](https://github.com/pleiszenburg/zugbruecke/blob/3cf84f9a27941de066e90944f5160c4fe77e4936/tests/test_memsync_computed_length.py#L87).

**Comment by JuliaSprenger** [comment]
Hello @s-m-e I think the main difference I am struggling with is that in my case there is no explicit additional argument that specifies the length of the arrays (or can be used to calculate the length). That's why I tried to compute the length on the fly using the pointer argument itself: `func=lambda x: len(x)` with using `'p'=[3]; 'l'=[3]` to compute the length of the array. Is it possible to do something like this using `zugbruecke`?

Originally I also tried to extract the length of the argument beforehand and adjust the `argtypes` specification each time before calling the dll function, this is why the `argtype` and `memsync` specification was in the for loop. However, it looked to me like once `argtypes` is defined and used once, it is somehow cached and is not overwritten in the next iteration of the loop. Does this make sense and is this behaviour intended?

**Comment by s-m-e** [comment]
>  there is no explicit additional argument that specifies the length of the arrays (or can be used to calculate the length)

The best bad thing you can do is to estimate the maximum size of the array(s) (by trying via `wenv`) and going for fixed-length arrays with sufficient margins. This really is not satisfactory though ... 

An alternative that I have played with in some instances is to treat the arrays as zero-terminated sequences of bytes (requires a lot of hackery). Not every DLL function terminates an array with a clean zero though and its not even possible in all scenarios. 

So strictly speaking something like `zugbruecke` would need *some kind* of indication of where the section of memory that contains the array ends or it will either miss stuff when synchronizing between the two processes or overshoot, causing anything ranging from memory protection errors to even segmentation faults. If you can figure out *any* kind of indication on its length, i.e. some specific characteristic in the data perhaps or in another parameter, this would be a potential path forward. You're parsing files if I understand the application correctly, so maybe the sizes of the files allows you to estimate the sizes of the arrays or similar.

> However, it looked to me like once argtypes is defined and used once, it is somehow cached and is not overwritten in the next iteration of the loop. Does this make sense and is this behaviour intended?

It's the behaviour of `ctypes` that `zugbruecke` basically inherits (it's still based on `ctypes` which is doing its thing in a separate Python process). `memsync` on the other hand relies on information from `argtypes` so once `argtypes` is set (and there is no more way to alter it anyway), `memsync` gets parsed one single time per function & session taking into account what was provided for `argtypes`.

**Comment by JuliaSprenger** [comment]
> So strictly speaking something like `zugbruecke` would need _some kind_ of indication of where the section of memory that contains the array ends or it will either miss stuff when synchronizing between the two processes or overshoot, causing anything ranging from memory protection errors to even segmentation faults. If you can figure out _any_ kind of indication on its length, i.e. some specific characteristic in the data perhaps or in another parameter, this would be a potential path forward. You're parsing files if I understand the application correctly, so maybe the sizes of the files allows you to estimate the sizes of the arrays or similar.

But for each dll method call the length is known as the argument provided is an array of a fixed length that will be modified by the dll method. Practically the length is extracted earlier via another dll method, then the fixed length array is constructed and provided as argument for the method discussed here. Shouldn't be the information about the length of the argument at runtime when calling the dll method sufficient for syncing the memory for each method call? Why does this need to be known from the beginning?

**Comment by s-m-e** [comment]
> Practically the length is extracted earlier via another dll method [...] Why does this need to be known from the beginning?

Does it need to be: No. I just simply never encountered this use case before, but it makes a ton of sense. `zugbruecke` can not handle this the way you describe it at the moment but it can probably be done with *relative* ease. Let me think about it. I would probably need to add a distinct argument to `memsync` that allows to dynamically pass length information, i.e. simple integers via a Python function handle provided by the user that can be called once per DLL function call by `zugbruecke`.

Just for comparison, the problem with fixed-length arrays the way `ctypes` (and therefore `zugbruecke`) handles them is that their length is really *fixed*, i.e. fixed at the time of setting it in `argtypes`. You can not adjust the fixed length once per function call. Fixed-length arrays do have a length in Python terms (i.e. an implementation of the `__len__` method as required by `len`) but this really does not help in your use case. With pure `ctypes` you could simply play with type casts and get it done but this is not viable with `zugbruecke`'s current implementation.

**Comment by JuliaSprenger** [comment]
The good news is that I got the minimal failing example to work now assuming that argument 2 is used to provide the correct array length as input argument. Now I just need to make sure that this is always the case in my code.
I was also missing some type casting of the input pointers to make these compatible with the `argtypes` specifications. Thanks for providing an example [showing this](https://github.com/pleiszenburg/zugbruecke/blob/3cf84f9a27941de066e90944f5160c4fe77e4936/tests/test_memsync_computed_length.py#L107). I hope this will be the last issue for now, but I will keep this thread open for a while - just in case.

**Comment by JuliaSprenger** [comment]
The [PR](https://github.com/NeuralEnsemble/python-neo/pull/1214) underlying the issue here has been merged, so I will close the discussion here. Thanks again for help and patience!

**Comment by s-m-e** [comment]
That's amazing! Thanks for the feedback.
